const translator = {
  initMoney: 'مقدار پول اولیه',
  initCoin: 'مقدار سکه اولیه',
  inviteMoney: 'مقدار پول معرفی',
  inviteCoin: 'مقدار سکه معرفی',
  completeInfoMoney: 'مقدار پول برای تکمیل اطلاعات',
  completeInfoCoin: 'مقدار سکه برای تکمیل اطلاعات',
  quizMoney: 'مقدار پول جایزه برای نفرات برتر',
  quizCoin: 'مقدار سکه جایزه برای نفرات برتر',
  agentOffPercent: 'تخفیف ثبت نام نماینده ها',
  schoolOffPercent: 'تخفیف ثبت نام مدارس',
  minRequestMoney: 'حداقل پول قابل برداشت',
  coinRateCoef: 'نرخ تبدیل سکه به پول',
  topInQuizForCert: 'تعداد نفرات برتر برای صدور گواهی',
  advisorOffPercent: 'تخفیف ثبت نام مشاوران',
  hermans: ' قیمت آزمون هرمنس',
  cattell: ' قیمت تست شخصیت شناسی ۱۶ عاملی کتل',
  LASSI: ' قیمت تست استاندارد راهبردهای مطالعه و یادگیری (LASSI)',
  beckDep: ' قیمت تست افسردگی بک',
  beckAnx: 'قیمت تست اضطراب بک',
  CDI: 'قیمت تست افسردگی ماریاکواس',
  MBTI: 'قیمت تست تیپ شخصیتی MBTI',
  standardRaven: 'قیمت آزمون هوش ریون استاندارد',
  proRaven: 'قیمت آزمون هوش ریون پیشرفته',
  childRaven: 'قیمت آزمون هوش ریون کودکان',
  gardner: 'قیمت تست هوش چندگانه گاردنر(MII)',
  izenk: 'قیمت تست شخصیت آیزنک (EPQ)',
  haland: 'قیمت آزمون رغبت سنج شغلی/تحصیلی هالند',
  neo: 'قیمت تست شخصیت شناسی نئو',
  cannor: 'قیمت تست هراس اجتماعی کانور',
  GHQ: 'قیمت تست سلامت عمومی ( GHQ )',
  RCMAS: 'قیمت آزمون اضطراب آشکار کودکان رینولدز و ریچموند',
  maxStudentQuizPerDay: 'حداکثر تعداد دانش آموز برای برگزاری آزمون در روز',
  quizPerStudentPrice: 'قیمت شرکت هر دانش آموز در آزمون های مدرسه ای',
  giftPeriod: 'بازه شرکت در گردونه شانس',
  minQuestionForCustomQuiz: 'حد آستانه سوالات در مباحث برای آزمون های شخصی ساز',
};

export default translator;
