const translator = {
  initMoney: 'مقدار پول اولیه',
  initCoin: 'مقدار ایکس پول اولیه',
  inviteMoney: 'مقدار پول معرفی',
  inviteCoin: 'مقدار ایکس پول معرفی',
  completeInfoMoney: 'مقدار پول برای تکمیل اطلاعات',
  completeInfoCoin: 'مقدار ایکس پول برای تکمیل اطلاعات',
  quizMoney: 'مقدار پول جایزه برای نفرات برتر',
  quizCoin: 'مقدار ایکس پول جایزه برای نفرات برتر',
  agentOffPercent: 'تخفیف ثبت نام نماینده ها',
  schoolOffPercent: 'تخفیف ثبت نام مدارس',
  minRequestMoney: 'حداقل پول قابل برداشت',
  coinRateCoef: 'نرخ تبدیل ایکس پول به پول',
  moneyRateCoef: 'نرخ تبدیل پول به ایکس پول',
  topInQuizForCert: 'تعداد نفرات برتر برای صدور گواهی',
  advisorOffPercent: 'تخفیف ثبت نام مشاوران',
  hermans: ' قیمت آزمون هرمنس',
  cattell: ' قیمت تست شخصیت شناسی ۱۶ عاملی کتل',
  LASSI: ' قیمت تست استاندارد راهبردهای مطالعه و یادگیری (LASSI)',
  beckDep: ' قیمت تست افسردگی بک',
  beckAnx: 'قیمت تست اضطراب بک',
  CDI: 'قیمت تست افسردگی ماریاکواس',
  MBTI: 'قیمت تست تیپ شخصیتی MBTI',
  standardRaven: 'قیمت آزمون هوش ریون استاندارد',
  proRaven: 'قیمت آزمون هوش ریون پیشرفته',
  childRaven: 'قیمت آزمون هوش ریون کودکان',
  gardner: 'قیمت تست هوش چندگانه گاردنر(MII)',
  izenk: 'قیمت تست شخصیت آیزنک (EPQ)',
  haland: 'قیمت آزمون رغبت سنج شغلی/تحصیلی هالند',
  neo: 'قیمت تست شخصیت شناسی نئو',
  cannor: 'قیمت تست هراس اجتماعی کانور',
  GHQ: 'قیمت تست سلامت عمومی ( GHQ )',
  RCMAS: 'قیمت آزمون اضطراب آشکار کودکان رینولدز و ریچموند',
  maxStudentQuizPerDay: 'حداکثر تعداد دانش آموز برای برگزاری آزمون در روز',
  maxQuestionPerQuiz: 'حداکثر تعداد سوال در هر آزمون مدرسه ای',
  quizPerStudentPrice: 'قیمت شرکت هر دانش آموز در آزمون‌های مدرسه ای',
  giftPeriod: 'بازه شرکت در گردونه شانس',
  minQuestionForCustomQuiz: 'حد آستانه سوالات در مباحث برای آزمون‌های شخصی ساز',
  firstRankCert: 'گواهی نفر اول',
  secondRankCert: 'گواهی نفر دوم',
  thirdRankCert: 'گواهی نفر سوم',
  forthRankCert: 'گواهی نفر چهارم',
  fifthRankCert: 'گواهی نفر پنجم',
  minAdvicePrice: 'حداقل هزینه برای پکیج مالی مشاور',
  maxVideoCallPerMonth: 'حداکثر تعداد تماس تصویری در ماه توسط هر مشاور',
  hwPerStudentPrice: 'قیمت هر دانش آموز در تمرین‌ها',
  minBuyAmountForShop: 'حداقل میزان خرید از فروشگاه برای گرفتن اعتبار',
  percentOfShopBuy: 'درصد از خرید فروشگاه',
  createShopOffVisibility:
    'آیا قابلیت گرفتن اعتبار با خرید از فروشگاه فعال باشد؟',
};

export default translator;
