const translator = {
  initMoney: 'مقدار پول اولیه',
  initCoin: 'مقدار سکه اولیه',
  inviteMoney: 'مقدار پول معرفی',
  inviteCoin: 'مقدار سکه معرفی',
  completeInfoMoney: 'مقدار پول برای تکمیل اطلاعات',
  completeInfoCoin: 'مقدار سکه برای تکمیل اطلاعات',
  quizMoney: 'مقدار پول جایزه برای نفرات برتر',
  quizCoin: 'مقدار سکه جایزه برای نفرات برتر',
  agentOffPercent: 'تخفیف ثبت نام نماینده ها',
  schoolOffPercent: 'تخفیف ثبت نام مدارس',
  minRequestMoney: 'حداقل پول قابل برداشت',
  coinRateCoef: 'نرخ تبدیل سکه به پول',
  topInQuizForCert: 'تعداد نفرات برتر برای صدور گواهی',
  advisorOffPercent: 'تخفیف ثبت نام مشاوران',
  hermans: 'آزمون هرمنس',
  cattell: 'تست شخصیت شناسی ۱۶ عاملی کتل',
  LASSI: 'تست استاندارد راهبردهای مطالعه و یادگیری (LASSI)',
  beckDep: 'تست افسردگی بک',
  beckAnx: 'تست اضطراب بک',
  CDI: 'تست افسردگی ماریاکواس',
  MBTI: 'تست تیپ شخصیتی MBTI',
  standardRaven: 'آزمون هوش ریون استاندارد',
  proRaven: 'آزمون هوش ریون پیشرفته',
  childRaven: 'آزمون هوش ریون کودکان',
  gardner: 'تست هوش چندگانه گاردنر(MII)',
  izenk: 'تست شخصیت آیزنک (EPQ)',
  haland: 'آزمون رغبت سنج شغلی/تحصیلی هالند',
  neo: 'تست شخصیت شناسی نئو',
  cannor: 'تست هراس اجتماعی کانور',
  GHQ: 'تست سلامت عمومی ( GHQ )',
  RCMAS: 'آزمون اضطراب آشکار کودکان رینولدز و ریچموند',
  maxStudentQuizPerDay: 'حداکثر تعداد دانش آموز برای برگزاری آزمون در روز',
  quizPerStudentPrice: 'قیمت شرکت هر دانش آموز در آزمون های مدرسه ای',
  giftPeriod: 'بازه شرکت در گردونه شانس',
};

export default translator;
