export const Translator = {
  buy: 'خرید محتوا',
  packageDuration: 'مدت دوره',
  sessionsCount: 'تعداد جلسات',
  chaptersCount: 'تعداد فصول',
  cert: 'گواهی دوره',
  certDuration: 'مهلت کسب گواهی',
  teacher: 'نام استاد',
  teacherBio: 'درباره مدرس',
  select: 'انتخاب دوره',
  preReq: 'پیش نیازهای دوره',
  desc: 'توضیحات دوره',
  sessions: 'جلسات',
  chapters: 'فصول',
  loginForBuy: 'ورود به سامانه برای خرید',
  faq: 'پرسش و پاسخ های متداول',
  off: 'تخفیف',
  publicOff: 'هدیه آیریسک',
  wallet: 'کیف پول',
};
