const Translator = {
  weekStartAt: 'روز شروع هفته',
  settledAt: 'تاریخ تسویه',
  schedulesSum: 'مجموع ساعات برنامه ریزی شده',
  doneSum: 'مجموع ساعات انجام شده',
  advisors: 'مشاور/مشاوران',
  create: 'ایجاد برنامه جدید',
  update: 'ویرایش برنامه',
  teachMode: 'نحوه تدریس',
  price: 'هزینه جلسه (به تومان - اختیاری)',
  packagePrice: 'هزینه تمامی جلسات (به تومان - اجباری)',
  iryscPercent: 'درصد آیریسک از تدریس',
  teacherShare: 'سهم دبیر',
  duration: 'مدت جلسه (به دقیقه)',
  title: 'عنوان (اختیاری)',
  mandatoryTitle: 'عنوان (اجباری)',
  needRegistryConfirmation:
    'آیا درخواست\u200cها نیاز به تایید شما داشته باشند؟',
  needRegistryConfirmationForStudents:
    'پرداخت و ثبت‌نام نهایی در این کلاس پس از تأیید معلم انجام می‌شود.',
  prePayWarning:
    'برای ذخیرۀ جای شما در این کلاس، مبلغ پیش ثبت‌نام دریافت می‌شود.',
  minCap: 'حداقل ظرفیت',
  maxCap: 'حداکثر ظرفیت',
  description: 'توضیحات (اختیاری)',
  start: 'روز و ساعت کلاس',
  studentsCount: 'تعداد دانش آموزان',
  requestsCount: 'تعداد درخواست\u200cها',
  private: 'خصوصی',
  semiPrivate: 'گروهی',
  answerAt: 'زمان پاسخ دبیر',
  expireAt: 'مهلت بررسی/پرداخت',
  createdAt: 'زمان درخواست',
  activeMode: 'وضعیت برگزاری جلسه',
  active: 'شروع نشده',
  expired: 'برگزار شده',
  registryStauts: 'وضعیت ثبت نامی\u200cها',
  requestStauts: 'وضعیت درخواست\u200cها',
  studentsList: 'لیست دانش آموزان',
  teacher: 'مدرس',
  status: 'وضعیت درخواست',
  pending: 'در حال بررسی',
  reject: 'رد شده',
  paid: 'پرداخت شده',
  cancel: 'انصراف داده شده',
  accept: 'تایید شده و در انتظار پرداخت',
  waitForCap: 'پرداخت پیش‌ثبت‌نام و در انتظار رسیدن حدنصاب',
  waitForPaySemiPrivate: 'کلاس به حدنصاب رسیده و در انتظار پرداخت',
  answered: 'پاسخ داده شده',
  unknown: 'نامشخص',
  copy: 'کپی کردن برنامه تدریس',
  buildSkyRoom: 'ساخت لینک جلسه در اسکای روم',
  goToSkyRoom: 'رفتن به اتاق تدریس در اسکای روم',
  seeStudentProfile: 'مشاهده اطلاعات تحصیلی دانش آموز',
  report: 'گزارش مشکل',
  comment: 'نوشتن نظر',
  teacherToStdRate: 'امتیاز شما به دانش آموز',
  teacherToStdRateAt: 'زمان امتیاز شما به دانش آموز',
  stdTeachRate: 'امتیاز دبیران به دانش آموز',
  requestsCountForStudents: 'درخواست\u200cها',
  individual: 'تک جلسه',
  multi: 'چند جلسه',
  sessionsMode: 'نوع تعداد جلسه',
  sessionsCount: 'تعداد جلسات',
  endRegistration: 'تاریخ اتمام ثبت نام',
  startDate: 'تاریخ شروع کلاس',
  endDate: 'تاریخ اتمام کلاس',
};

export default Translator;
