const Translator = {
  weekStartAt: 'روز شروع هفته',
  schedulesSum: 'مجموع ساعات برنامه ریزی شده',
  doneSum: 'مجموع ساعات انجام شده',
  advisors: 'مشاور/مشاوران',
  create: 'ایجاد برنامه جدید',
  update: 'ویرایش برنامه',
  teachMode: 'نحوه تدریس',
  price: 'هزینه جلسه (به تومان - اختیاری)',
  duration: 'مدت جلسه (به دقیقه)',
  title: 'عنوان (اختیاری)',
  needRegistryConfirmation: 'آیا درخواست ها نیاز به تایید شما داشته باشند؟',
  needRegistryConfirmationForStudents: 'نیاز به تایید توسط دبیر بعد از درخواست',
  minCap: 'حداقل ظرفیت',
  maxCap: 'حداکثر ظرفیت',
  description: 'توضیحات (اختیاری)',
  start: 'روز و ساعت برگزاری جلسه',
  studentsCount: 'تعداد دانش آموزان',
  requestsCount: 'تعداد درخواست ها',
  private: 'خصوصی',
  semiPrivate: 'نیمه خصوصی',
  answerAt: 'زمان پاسخ دبیر',
  expireAt: 'مهلت بررسی/پرداخت',
  createdAt: 'زمان درخواست',
  activeMode: 'وضعیت برگزاری جلسه',
  registryStauts: 'وضعیت ثبت نامی ها',
  requestStauts: 'وضعیت درخواست ها',
  studentsList: 'لیست دانش آموزان',
  teacher: 'مدرس',
  status: 'وضعیت درخواست',
  pending: 'در حال بررسی',
  reject: 'رد شده',
  paid: 'پرداخت شده',
  cancel: 'انصراف داده شده',
  accept: 'تایید شده و در انتظار پرداخت',
  answered: 'پاسخ داده شده',
  unknown: 'نامشخص',
  copy: 'کپی کردن برنامه تدریس',
  buildSkyRoom: 'ساخت لینک جلسه در اسکای روم',
  goToSkyRoom: 'رفتن به اتاق تدریس در اسکای روم',
};

export default Translator;
