const translator = {
  generalInfo: 'اطلاعات آزمون',
  quizes: 'آزمون های موجود',
  name: 'نام آزمون',
  kind: 'نوع آزمون',
  tag: 'تگ های جست و جو',
  runInfo: 'اطلاعات اجرا',
  registryInfo: 'اطلاعات ثبت نام',
  answerSheetInfo: 'اطلاعات پاسخ نامه',
  startDate: 'تاریخ و زمان شروع',
  endDate: 'تاریخ و زمان پایان',
  startRegistryDate: 'تاریخ و زمان شروع ثبت نام',
  endRegistryDate: 'تاریخ و زمان پایان ثبت نام',
  price: 'قیمت آزمون',
  ranking: 'تعداد نفرات برتر',
  isOnline: 'نوع اجرا',
  len: 'مدت آزمون (به دقیقه)',
  questionBased: 'بر اساس سوالات',
  isRegistrable: 'آیا این آزمون توسط دانش آموزان قابل خریداری است؟',
  isUploadable: 'آیا پاسخ توسط دانش آموز قابل بارگذاری است؟',
  isQRNeeded: 'آیا فرآیند تصحیح با QR انجام میگیرد؟',
  online: 'آنلاین',
  offline: 'حضوری',
  capacity: 'ظرفیت آزمون',
  permute: 'آیا سوالات بر زده شود؟',
  backEn: 'آیا بازگشت به سوال قبل امکان پذیر باشد؟',
  minusMark: 'آیا آزمون نمره منفی داشته باشد؟',
  useFromDatabase: 'آیا از مجموعه سوالات آیریسک استفاده می شود؟',
  showResultAfterCorrection:
    'آیا نتایج بعد از صدور تراز به دانش آموزان نمایش داده شود؟',
  showResultsAfterCorrectionNotLoginUsers:
    'آیا نتایج بعد از صدور تراز به کاربران ورود نکرده نمایش داده شود؟',
  descBefore: 'توضیحات قبل از آزمون (این فیلد اختیاری است)',
  descAfter: 'توضیحات بعد از آزمون (این فیلد اختیاری است)',
  uploadFile: 'بارگذاری فایل جهت درج در ckeditor (اختیاری)',
  seeInfo: 'مشاهده اطلاعات',
  editQuestions: 'ویرایش سوالات',
  editQuestion: 'ویرایش سوال',
  seeQuestion: 'مشاهده سوالات',
  studentsList: 'مشاهده لیست دانش آموزان',
  forceRegistry: 'ثبت نام مستقیم',
  createTaraz: 'ساخت تراز',
  gift: 'اهدا جوایز',
  transferToOpenQuiz: 'انتقال به آزمون باز',
  studentsListInQuiz: 'لیست دانش آموزان آزمون ',
  addStudent: 'اضافه کردن دانش آموز',
  deleteStudent: 'حذف دانش آموز',
  chooseQuestion: 'انتخاب سوال',
  questions: 'سوالات آزمون',
  organizationId: 'کد سازمانی سوال',
  organizationIdHelp: 'چندین کد را با استفاده از , جدا کنید',
  topic: 'موضوع',
  mark: 'نمره سوال',
  generateQuestionPDF: 'دانلود دفترچه آزمون',
  generateAnswerSheetPDF: 'دانلود دفترچه پاسخبرگ',
  correntAnswerSheets: 'تصحیح پاسخ برگ های اسکن شده',
  keySheet: 'کلید آزمون',
  correctors: 'مصححین',
  addCorrector: 'افزودن مصحح',
  seeRanking: 'مشاهده نتایج',
  changeSort: 'تغییر ترتیب سوالات',
  startDateFrom: 'بازه شروع',
  startDateEnd: 'اتمام بازه شروع',
  startRegistryDateFrom: 'بازه شروع ثبت نام',
  startRegistryDateEnd: 'اتمام بازه شروع ثبت نام',
  copyLink: 'کپی کردن لینک اختصاصی ثبت نام',
  seeMyTasks: 'مشاهده دانش آموزان / سوالات',
  addTask: 'افزودن دانش آموزان / سوالات',
  studentList: 'لیست دانش آموزان',
  questionList: 'لیست سوالات',
  finalize: 'نهایی سازی آزمون',
  recp: 'مشاهده فاکتور',
  copy: 'کپی کردن آزمون',
  copyStudents: 'کپی کردن دانش آموزان',
  finalizeMsg:
    'توجه داشته باشید که بعد از نهایی سازی آزمون امکان ویرایش لیست نفرات شرکت کننده و یا سوالات وجود ندارد.',
  payByStudent: 'آیا هزینه آزمون توسط دانش آموزان پرداخت شود؟',
  maxTeams: 'حداکثر تعداد تیم ها',
  perTeam: 'حداکثر تعداد نفرات در هر تیم',
  teamName: 'نام تیم',
  members: 'اعضای تیم',
  sureChangeMainMember: 'آیا از تغییر نفر اصلی اطمینان دارید؟',
};

export default translator;
