const Translate = {
  number: 'شماره',
  addBookmark: 'بعد فکر می کنم',
  deleteBookmark: 'حذف نشان سوال',
  description: 'شرح سوال',
  answerFile: 'پاسخ تشریحی',
  res: 'انتخاب پاسخ',
  yourAnswer: 'پاسخ شما',
  answer: 'پاسخ صحیح',
  choice: 'گزینه ',
  sentence: 'گزاره ',
  resInput: 'ورود پاسخ',
  status: 'وضعیت کلی',
  questionRes: 'سوالات پاسخ داده شده ',
  questionNoAnswer: 'سوالات بدون پاسخ',
  review: 'مرور آزمون',
  continue: 'ادامه آزمون',
  start: 'مشاهده سوالات',
  next: 'بعدی',
  prev: 'قبلی',
  finish: 'پایان آزمون',
  totalTime: 'زمان کل آزمون',
  quizList: 'نقشه آزمون',
  help: 'راهنما',
  answered: 'جواب دادی',
  notAnswered: 'جواب ندادی',
  bookmarked: 'می خوای فکر کنی',
  reminder: ' وقت داری ',
};

export default Translate;
