const certTranslator = {
  certName: 'نام گواهی',
  certType: 'نوع گواهی:',
  transverseDistance: 'فاصله عرضی',
  longitudinalDistance: 'فاصله طولی',
  qrSize: 'QR سایز',
  fromRightScreen: 'از سمت راست صفحه',
  fromTopScreen: 'از سمت بالای صفحه',
  createNewCert: 'ایجاد گواهی جدید',
  dynamicParameters: 'پارامترهای دینامیک',
  selectParameters: 'انتخاب پارامتر',
  fontType: 'نوع فونت',
  fontSize: 'سایز فونت',
  rightDistance: 'فاصله از راست عدد',
  offset: 'آفست*',
  normalOrBold: 'معمولی یا بولد',
  matchingWord: 'word مطابق سایز',
  fileNotSelect: 'هنوز فایلی انتخاب نشده است',
  formate: 'فرمت:',
  fortyPercent: '40%',
  haveCertificate: 'گواهی های موجود ',
  createDate: 'تاریخ ایجاد',
  receiver: 'دریافت کننده',
  vertical: 'عمودی',
  horizontal: 'افقی',
  center: 'مرکز',
};

export default certTranslator;
