const certTranslator = {
  certName: 'نام گواهی',
  certType: 'نوع گواهی:',
  horizontalDistance: 'فاصله عرضی',
  verticalDistance: 'فاصله طولی',
  qrSize: 'QR سایز',
  fromRightScreen: 'از سمت راست صفحه',
  fromTopScreen: 'از سمت بالای صفحه',
  createNewCert: 'ایجاد گواهی جدید',
  dynamicParameters: 'پارامترهای دینامیک',
  paramName: 'انتخاب پارامتر',
  fontType: 'نوع فونت',
  fontSize: 'سایز فونت',
  rightDistance: 'محاسبه بر اساس فاصله از راست',
  offset: 'آفست*',
  normalOrBold: 'معمولی یا Bold',
  matchingWord: ' مطابق سایز World',
  fileNotSelect: 'هنوز فایلی انتخاب نشده است',
  formate: 'فرمت:',
  fortyPercent: '40%',
  haveCertificate: 'گواهی های موجود ',
  createDate: 'تاریخ ایجاد',
  receiver: 'دریافت کننده',
  vertical: 'عمودی',
  horizontal: 'افقی',
  center: 'محاسبه بر اساس مرکز',
  param: 'پرامتر',
  typeOfFont: 'نوع فونت',
  selectFiles: 'هنوز فایلی انخاب نشده است - نام فایل*',
  addStudent: 'افزودن نفرات به گواهی',
};

export default certTranslator;
