export const Translate = {
  dashboard: 'داشبورد مشاوران',
  studentsCountForAdvice: 'تعداد دانش آموزان برای مشاوره',
  studentsCountForTeach: 'تعداد دانش آموزان برای تدریس',
  pendingExamsForPay: 'تعداد آزمون‌های در انتظار پرداخت',
  lastMonthCreatedExams: 'تعداد آزمون‌های ساخته شده در 30 روز اخیر',
  lastMonthMeetings: 'تعداد جلسات آنلاین در 30 روز اخیر',
  lastMonthKarbargs: 'تعداد کاربرگ‌ها در 30 روز اخیر',
  sendFrom: 'ارسال شده از جانب',
  sendTo: 'ارسال شده برای',
  wantedPackageTitle: 'بسته موردنظر برای مشاوره',
  wantedPackagePrice: 'هزینه بسته',
  requestAt: 'زمان ارسال درخواست',
  answerAt: 'زمان ارسال پاسخ',
  requestStatus: 'وضعیت درخواست',
  newRequests: 'درخواست‌های مشاوره جدید',
  lastComments: 'نظرات اخیر درباره من',
  myCurrStudents: 'دانش آموزان من برای مشاوره',
  lastUnSeenTickets: 'آخرین تیکت‌های مشاهده نشده',
  lastMonthSettled: 'مجموع مبالغ تسویه شده در 30 روز اخیر',
  inProgressKarbargs: 'کاربرگ‌های در حال تدوین',
  filledSchedules: 'کاربرگ‌های تکمیل شده توسط دانش آموزان',
  pendingSettled: 'تعداد تراکنش‌های درانتظار پرداخت',
  stats: 'آمار کلی',
  showLastSettleRequest: 'نمایش آخرین تسویه انجام شده',
  showInProgressKarbargs: 'نمایش کاربرگهای تکمیل نشده',
  showFilledKarbargs: 'نمایش کاربرگهای تکمیل شده توسط دانش آموزان',
  showMyLastComments: 'نمایش آخرین کامنت‌های درباره من',
  showIncomingRequestsForAdvice: 'نمایش درخواست‌های مشاوره رسیده',
  showIncomingRequestsForTeach: 'نمایش درخواست‌های رسیده برای تدریس',
  showDashboard: 'نمایش آمار کلی',
  showLastNotifs: 'نمایش آخرین اعلانات',
  showMyAdviceStudents: 'نمایش دانش آموزان من برای مشاوره',
  showMyFutureTeaches: 'نمایش تدریس‌های هفته جاری',
  showLastTickets: 'نمایش آخرین تیکت‌ها',
  weekStartAt: 'شروع برنامه',
  studentName: 'نام دانش آموز',
  advisors: 'مشاوران',
  currMeetings: 'جلسات آنلاین شما',
  meetingStartAt: 'تاریخ شروع جلسه',
  meetingEndAt: 'تاریخ اتمام جلسه',
  meetingStudent: 'دانش آموز جلسه',
  meetingUrl: 'لینک ورود به جلسه',
  startAdviceAt: 'زمان شروع مشاوره',
  endAdviceAt: 'زمان اتمام مشاوره',
};
