export const Translate = {
  dashboard: 'داشبورد مشاوران',
  studentsCountForAdvice: 'تعداد دانش آموزان برای مشاوره',
  studentsCountForTeach: 'تعداد دانش آموزان برای تدریس',
  pendingExamsForPay: 'تعداد آزمون‌های در انتظار پرداخت',
  lastMonthCreatedExams: 'تعداد آزمون‌های ساخته شده در 30 روز اخیر',
  lastMonthMeetings: 'تعداد جلسات آنلاین در 30 روز اخیر',
  lastMonthKarbargs: 'تعداد کاربرگ‌ها در 30 روز اخیر',
  sendFrom: 'ارسال شده از جانب',
  wantedPackageTitle: 'بسته موردنظر برای مشاوره',
  wantedPackagePrice: 'هزینه بسته',
  requestAt: 'زمان ارسال درخواست',
  newRequests: 'درخواست‌های مشاوره جدید',
  lastNotifs: 'اعلانات اخیر دیده نشده',
  lastComments: 'نظرات اخیر درباره من',
  lastUnSeenTickets: 'آخرین تیکت‌های مشاهده نشده',
  lastMonthSettled: 'مجموع مبالغ تسویه شده در 30 روز اخیر',
  inProgressKarbargs: 'کاربرگ‌های در حال تدوین',
  pendingSettled: 'تعداد تراکنش‌های درانتظار پرداخت',
  stats: 'آمار کلی',
  showLastSettleRequest: 'نمایش آخرین تسویه انجام شده',
  showInProgressKarbargs: 'نمایش کاربرگهای تکمیل نشده',
  showFilledKarbargs: 'نمایش کاربرگهای تکمیل شده توسط دانش آموزان',
  showMyLastComments: 'نمایش آخرین کامنت‌های درباره من',
  showIncomingRequestsForAdvice: 'نمایش درخواست‌های مشاوره رسیده',
  showIncomingRequestsForTeach: 'نمایش درخواست‌های رسیده برای تدریس',
  showDashboard: 'نمایش آمار کلی',
  showLastNotifs: 'نمایش آخرین اعلانات',
  showLastTickets: 'نمایش آخرین تیکت‌ها',
  weekStartAt: 'شروع برنامه',
  studentName: 'نام دانش آموز',
};
