const translator = {
  offs: 'کد های تخفیف',
  addOff: 'افزودن کد تخفیف',
  editOff: 'ویرایش کد تخفیف',
  amount: 'مقدار کد تخفیف',
  code: 'کد',
  type: 'نوع کد تخفیف',
  withOrWithOutCode: 'با/بدون کد',
  withCode: 'با کد',
  withoutCode: 'بدون کد',
  value: 'مقداری',
  percent: 'درصدی',
  expire: 'تاریخ انقضا',
  usedCount: 'تعداد استفاده',
  useAt: 'زمان استفاده',
  used: 'استفاده شده',
  notUsed: 'استفاده نشده',
  usedAndNotUsed: 'استفاده شده یا نشده',
  isPublic: 'آیا این کد تخفیف عمومی است؟',
  isPublicFilter: 'همگانی/غیر همگانی',
  gachExam: 'آزمون‌های آیریسک',
  bankExam: 'آزمون‌های شخصی ساز',
  book: 'فروش کتاب',
  schoolQuiz: 'آزمون مدرسه ای',
  classes: 'فروش دوره و کلاس',
  ravanExam: 'آزمون‌های روان شناسی',
  counseling: 'مشاوره',
  expired: 'منقضی شده',
  startUseOffCode: 'شروع بازه استفاده کد تخفیف',
  endUseOffCode: 'اتمام بازه استفاده کد تخفیف',
  startExpireOffCode: 'شروع بازه منقضی شدن کد تخفیف',
  endExpireOffCode: 'اتمام بازه منقضی شدن استفاده کد تخفیف',
  content: 'بسته های آموزشی',
};

export default translator;
