const translator = {
  offs: 'کد های تخفیف',
  addOff: 'افزودن کد تخفیف',
  editOff: 'ویرایش کد تخفیف',
  amount: 'مقدار کد تخفیف',
  code: 'کد',
  type: 'نوع کد تخفیف',
  withOrWithOutCode: 'با/بدون کد',
  withCode: 'با کد',
  withoutCode: 'بدون کد',
  value: 'مقداری',
  percent: 'درصدی',
  expire: 'تاریخ انقضا',
  usedCount: 'تعداد استفاده',
  useAt: 'زمان استفاده',
  used: 'استفاده شده',
  notUsed: 'استفاده نشده',
  usedAndNotUsed: 'استفاده شده یا نشده',
  isPublic: 'آیا این کد تخفیف عمومی است؟',
  isPublicFilter: 'همگانی/غیر همگانی',
  gachExam: 'آزمون های آیریسک',
  bankExam: 'آزمون های شخصی ساز',
  book: 'فروش کتاب',
  classes: 'فروش دوره و کلاس',
  ravanExam: 'آزمون های روان شناسی',
  counseling: 'مشاوره',
};

export default translator;
