const translator = {
  allRequests: 'لیست درخواست ها',
  seeForm: 'مشاهده فرم اطلاعات',
  status: 'وضعیت درخواست',
  pending: 'در حال بررسی',
  finished: 'اتمام یافته',
  showRequest: 'مشاهده ی درخواست',
  showRecords: 'مشاهده ی سوابق',
  closeRecords: 'بستن درخواست',
  titleSuggest: 'عنوان مربوطه',
  closedRequest: 'بسته شده',
  section: 'واحد',
  item: 'آیتم موردنظر',
  priority: 'ضرورت',
  dateStartRequest: 'بازه شروع درخواست از',
  dateEndRequest: 'بازه شروع درخواست تا',
  lastStartUpdate: 'آخرین بروزرسانی از',
  lastEndUpdate: 'آخرین بروزرسانی تا',
  startWith: 'شروع کننده',
  title: 'موضوع',
  msgText: 'متن پیام',
  create: 'ایجاد پیام جدید',
  searchArchive: 'جستجو در آرشیو :',
  sureClose: 'آیا از بستن آیتم/آیتم های موردنظر اطمینان دارید؟',
  successSendAnswer: 'پاسخ شما با موفقیت ذخیره شد.',
  insetYourMsg: 'لطفا متن پیام خود را وارد نمایید.',
  nameOfReciver: 'نام دریافت کننده',
  desc: 'متن درخواست',
  confrim: 'ارسال',
};

export default translator;
