const Translate = {
  username: 'کاربر درخواست دهنده',
  section: 'بخش',
  notSettlements: 'تسویه نشده',
  settlements: 'تسویه شده',
  transactions: 'سوابق تراکنش\u200cهای من',
  from: 'تاریخ آغاز فیلتر',
  to: 'تاریخ پایان فیلتر',
  settlementValues: 'نوع تسویه',
  totalSettled: 'مجموع مبالغ تسویه شده (به تومان) : ',
  totalPrice: 'مجموع مبالغ سهم دبیر (به تومان) : ',
  requestSettlement: 'برای درخواست تسویه کلیک کنید',
  currSettlement: 'تسویه جاری',
  settlementHistory: 'تاریخچه درخواست\u200cهای تسویه',
  paid: 'پرداخت شده',
  waitForPay: 'در انتظار پرداخت',
  pending: 'در حال بررسی',
  reject: 'رد شده',
  paidAt: 'زمان پرداخت',
  answerFrom: 'زمان پاسخ گویی از',
  answerTo: 'زمان پاسخ گویی تا',
  changeStatus: 'تغییر وضعیت درخواست',
  newStatus: 'وضعیت جدید',
};

export default Translate;
