const Translate = {
  selectGift: 'انتخاب جایزه',
  giftType: 'نوع جایزه',
  amount: 'مقدار جایزه',
  probability: 'احتمال',
  library: 'کتابخانه',
  class: 'کلاس و همایش',
  psychology: 'آزمون های روان شناسی',
  useItem: 'مورد استفاده',
  maxCut: 'حداکثر تعداد برش ها',
  typeOffCode: 'نوع  تخفیف',
  percent: 'درصدی',
  values: 'مقداری',
  siteApp: 'سایت / اپ',
  site: 'سایت',
  app: 'اپ',
  launchDates: 'تاریخ های اجرا :',
  personalQuiz: 'ازمون های شخصی',
  gachQuiz: 'آزمون های گچ',
  content: 'بسته های آموزشی',
  counseling: 'مشاوره',
  newDate: 'تاریخ جدید',
  reminder: 'تعداد باقی مانده',
};

export default Translate;
