const translate = {
  startRegistery: 'آغاز مهلت ثبت نام ',
  endRegistery: 'اتمام مهلت ثبت نام ',
  startLaunching: 'آغاز زمان برگزاری ',
  endLaunching: 'اتمام زمان برگزاری ',
  reminder: 'ظرفیت باقی مانده: ',
  price: 'قیمت : ',
  studentsCount: 'تعداد ثبت نامی: ',
  duration: 'مدت آزمون',
  questionsCount: 'تعداد سوالات آزمون',
  isOnline: 'نوع اجرا: ',
  kind: 'نوع آزمون: ',
  mark: 'نمره: ',
  used: 'تعداد مرتبه تکرار در آزمون ها: ',
  oldWhite: 'تعداد نزده: ',
  oldCorrect: 'تعداد درست: ',
  oldIncorrect: 'تعداد نادرست: ',
  canUpload: ' آیا پاسخ باید آپلود شود؟ ',
  waitForResult: 'در انتظار صدور کارنامه باشید.',
  notStart: 'این آزمون هنوز شروع نشده است.',
  timeReminder: 'زمان باقی مانده',
  resultReady: 'کارنامه آزمون صادر شده است.',
  perTeam: 'حداکثر نفرات هر تیم',
};

export default translate;
