export const Translate = {
  advisorInfo: 'اطلاعات مشاور',
  studentsCount: 'تعداد دانش آموزان فعلی',
  totalStudentsCount: 'تعداد کل دانش آموزان',
  commentsCount: 'نظرات تایید شده درباره این مشاور',
  ratesCount: 'تعداد آرا داده شده',
  enter: 'ورود به اکانت',
  total: 'تعداد کل گزارشات',
  totalUnSeen: 'تعداد کل گزارشات بررسی نشده',
  mode: 'گزارش توسط کدامیک',
  sendFrom: 'ارسال شده از طرف',
  seenStatus: 'وضعیت مشاهده',
  advisor: 'مشاور',
  reporter: 'گزارش‌دهنده',
  reportAbout: 'گزارش‌شونده',
  detail: 'جزئیات',
  justUnSeen: 'فقط مشاهده نشده‌ها',
  videoLink: 'مشاهده ویدیو معرفی',
  meetingCount: 'تعداد جلسات آنلاین برگزار کرده',
  reportsCount: 'تعداد گزارشات مشکل از سمت دانش آموزان',
  totalSettlements: 'تعداد کل تسویه‌های انجام شده',
  totalSettledAmount: 'مبلغ کل تسویه انجام شده',
  schedulesCount: 'تعداد کل کاربرگ‌های طراحی شده',
  currentStudents: 'دانش آموزان فعلی',
  recentComments: 'کامنت‌های اخیر',
  recentReports: 'مشکل‌های گزارش‌‌های اخیر',
};
