export const Translate = {
  advisorInfo: 'اطلاعات مشاور',
  studentsCount: 'تعداد دانش آموزان فعلی',
  totalStudentsCount: 'تعداد کل دانش آموزان',
  commentsCount: 'نظرات تایید شده درباره این مشاور',
  ratesCount: 'تعداد آرا داده شده',
  enter: 'ورود به اکانت',
  total: 'تعداد کل گزارشات',
  totalUnSeen: 'تعداد کل گزارشات بررسی نشده',
  mode: 'گزارش توسط کدامیک',
  sendFrom: 'ارسال شده از طرف',
  seenStatus: 'وضعیت مشاهده',
  advisor: 'مشاور',
  reporter: 'گزارش‌دهنده',
  reportAbout: 'گزارش‌شونده',
  detail: 'جزئیات',
  justUnSeen: 'فقط مشاهده نشده‌ها',
};
