export const Translate = {
  youSee: 'شما در یک نگاه',
  money: 'کیف پول',
  passedQuizzes: 'آزمون‌های گذشته',
  createOff: 'ساخت کد تخفیف',
  activeQuizzes: 'آزمون‌های آینده',
  allQuizzes: 'آزمون آماده ثبت نام',
  yourRank: 'رتبه آیریسکی',
  yourBranchRank: 'رتبه در رشته',
  yourGradeRank: 'رتبه در پایه تحصیلی',
  counter: 'چند عدد',
  showCurrentKarbargs: 'نمایش کاربرگ جاری',
  showRequestsStatusForAdvice: 'نمایش وضعیت درخواست برای مشاور',
  showRequestsStatusForTeach: 'نمایش وضعیت درخواست برای تدریس',
  showLastTickets: 'نمایش تیکت‌های اخیر',
  showLastNotifs: 'نمایش اعلانات اخیر',
  showDashboard: 'نمایش آمار کلی',
  showSuggestionForContent: 'نمایش پیشنهادات برای خرید بسته‌های آموزشی',
  showSuggestionForQuiz: 'نمایش پیشنهادات برای خرید آزمون‌ها',
  showFutureQuiz: '(کمتر از 3 روز مانده به شروع آزمون)نمایش آزمون پیشرو',
  adviceRequests: 'درخواست‌های مشاوره اخیر',
  myAdvisors: 'مشاوران من',
};
