export const routes = {
  whichKindOfAuthIsAvailable: 'user/whichKindOfAuthIsAvailable?NID=',
  forgetPassword: 'user/forgetPassword',
  resetPassword: 'user/resetPassword',
  signup: 'user/signUp',
  activate: 'user/activate',
  resendCode: 'user/resendCode',
  updateInfo: 'user/updateInfo',
  fetchUser: 'user/fetchUser',
  checkCode: 'user/checkCode',
  sendRoleForm: 'user/sendRoleForm',
  fetchState: 'general/fetchStates',
  fetchSchoolsDigest: 'general/fetchSchoolsDigest',
  fetchGrades: 'admin/content/grades',
  fetchBranches: 'admin/content/branches',
};
