const translator = {
  username: 'نام کاربری',
  password: 'رمزعبور',
  rPassword: 'تکرار رمزعبور',
  confirm: 'تایید',
  phone: 'شماره تلفن همراه',
  mail: 'ایمیل',
  signUp: 'ثبت نام',
  NID: 'کد ملی',
  help: 'راهنما',
  firstname: 'نام',
  lastname: 'نام خانوادگی',
  congratulations: 'تبریک',
  chooseOne: 'لطفا یکی از گزینه های زیر را انتخاب کنید',
  student: 'دانش آموز',
  Certificat: 'گواهی',
  students: 'دانش آموزان',
  teacher: 'دبیر',
  teachers: 'دبیران',
  agent: 'نماینده',
  agents: 'نمایندگان',
  school: 'مدرسه',
  author: 'طراح',
  management: 'مدیریت',
  authors: 'مولفین',
  schools: 'مدارس',
  advisor: 'مشاور',
  price: 'قیمت :',
  priceUnit: 'تومان',
  advisors: 'مشاوران',
  entrance: 'ورود',
  continue: 'ادامه',
  support: 'پشتیبانی',
  email: 'آدرس ایمیل',
  home: 'خانه',
  dashboard: 'داشبورد',
  myGeneralQuizes: 'آزمون های من',
  myQuizes: 'آزمون های آیریسکی من',
  myCustomQuizess: 'آزمون های شخصی من',
  mySchoolQuizess: 'آزمون های مدرسه ای من',
  myStudentRequests: 'درخواست های پذیرش',
  mySchool: 'مدرسه من',
  packages: 'بسته های آموزشی',
  myPackages: 'بسته های آموزشی من',
  buyPackages: 'خرید بسته آمورشی',
  quiz: 'آزمون',
  buyQuiz: 'خرید آزمون',
  myAdvisor: 'مشاور من',
  makeQuiz: 'ساخت آزمون',
  quizes: 'آزمون ها',
  hws: 'تمارین',
  notifs: 'پیام های گروهی',
  innerNotifs: 'پیام های درون سایتی',
  mailNotifs: 'پیام های ایمیلی',
  smslNotifs: 'پیام های پیامکی',
  tag: 'تگ',
  avatars: 'مدیریت تصاویر آواتار',
  charge: 'شارژ کیف پول',
  myCerts: 'گواهی های من',
  history: 'سابقه',
  finantialHistory: 'سوابق مالی',
  config: 'تنظیمات',
  configuration: 'پیکربندی',
  generalConfiguration: 'پیکربندی کلی',
  certificateConfiguration: 'پیکربندی گواهی نفرات برتر',
  ravanConfiguration: 'پیکربندی آزمون های روان شناسی',
  requests: 'درخواست ها',
  requestsLog: 'تاریخچه درخواست ها',
  users: 'کاربران',
  pleaseFillAllFields: 'لطفا تمام فیلدهای لازم را پر نمایید.',
  invalidFieldValue: 'مقدار وارد شده صحیح نمی باشد.',
  opErr: 'خطایی در انجام عملیات موردنظر رخ داده است',
  noQuiz: 'آزمونی موجود نیست',
  noResult: 'نتیجه ای یافت نشد',
  necessary: 'ضروری',
  necessaryField: 'این فیلد ضروری است.',
  notNecessary: 'این فیلد ضروری نیست',
  cancel: 'انصراف',
  sex: 'جنسیت',
  state: 'استان',
  city: 'شهر',
  grade: 'پایه تحصیلی',
  lesson: 'درس',
  subject: 'حیطه',
  tel: 'شماره تماس',
  branch: 'رشته',
  change: 'تغییر',
  doChange: 'اعمال تغییر',
  confirmChanges: 'ثبت تغییرات',
  horizontal: 'افقی',
  vertical: 'عمودی',
  center: 'مرکز:',
  nextStep: 'مرحله بعد',
  desc: 'توضیحات',
  optional: 'اختیاری',
  ticket: 'درخواست پشتیبانی',
  nullAns: 'نزده',
  yes: 'بله',
  no: 'خیر',
  hide: 'عدم نمایش',
  show: 'نمایش',
  toHide: 'تغییر وضعیت نمایش به عدم نمایش',
  toShow: 'تغییر وضعیت نمایش به نمایش',
  optionalField: '(این فیلد اختیاری است)',
  optionalFalseDefault: 'اختیاری(پیش فرض این فیلد خیر است)',
  optionalTrueDefault: 'اختیاری(پیش فرض این فیلد بله است)',
  chooseFile: 'انتخاب فایل',
  uploading: 'در حال آپلود',
  offsBonus: 'تخفیف و جایزه',
  pleaseWait: 'لطفا شکیبا باشید',
  processRunnig: 'پروسه در حال اجرا',
  fileAdressFor: 'آدرس فایل آپلود شده برای',
  nesFile: 'توضیحات آزمون',
  copyLink: 'کپی کردن لینک',
  copied: 'کپی شد!',
  delete: 'حذف',
  upload: 'بارگذاری فایل',
  notChooseFile: 'هنوز فایلی انتخاب نشده است',
  maxSize: 'حداکثر حجم ',
  format: 'فرمت',
  success: 'عملیات موردنظر با موفقیت انجام شد',
  paid: 'مقدار پرداختی',
  searchBy: 'خصوصیت یکتا',
  nameAndLast: 'نام و نام خانوادگی',
  search: 'جست و جو',
  wantedUser: 'دانش آموز موردنظر',
  deleteAll: 'حذف همه',
  edit: 'ویرایش',
  opMenu: 'منو عملیات',
  op: 'عملیات کلی',
  operation: 'عملیات',
  sureRemove: 'آیا از حذف آیتم/آیتم های موردنظر اطمینان دارید؟',
  NIDs: 'کد ملی دانش آموزان مدنظر',
  NIDHelp: 'چندین کد ملی را با استفاده از , جدا کنید',
  createdAt: 'زمان ایجاد',
  advancedSearch: 'جستجوی پیشرفته',
  update: 'ویرایش',
  all: 'همه',
  pageNotFound: 'صفحه موردنظر یافت نشد.',
  sampad: 'سمپاد',
  gheyr: 'غیرانتفاعی',
  sayer: 'سایر',
  nemone: 'نمونه دولتی',
  heyat: 'هیئت امنایی',
  dolati: 'دولتی',
  aval: 'متوسطه اول',
  dovom: 'متوسطه دوم',
  dabestan: 'دبستان',
  address: 'آدرس',
  add: 'افزودن',
  access: 'دسترسی',
  status: 'وضعیت',
  searchUser: 'یافتن دانش آموز',
  changeStatus: 'تغییر وضعیت',
  changeLevel: 'تغییر سطح',
  changePassword: 'تغییر رمز عبور',
  repeat: 'تکرار',
  currentLevel: 'سطح فعلی',
  newLevel: 'سطح جدید',
  confrim: 'ثبت',
  basicDefinition: 'تعاریف پایه',
  gradeDefinition: 'تعریف مقاطع ',
  lessonsDefinition: 'تعریف دروس',
  subjectDefinition: 'تعریف حیطه',
  nameContent: 'نام محتوا',
  necessaryContent: 'توضیحات ضروری',
  title: 'عنوان',
  finantialManagement: 'مدیریت مالی',
  offcode: 'کد تخفیف',
  report: 'گزارشات',
  questionReport: 'گزارش خرابی سوال',
  logout: 'خروج',
  profile: 'پروفایل',
  hello: 'سلام',
  seeInfo: 'مشاهده اطلاعات',
  isOlympiad: 'آیا جز مقاطع تحصیلی است؟',
  listQuiz: 'لیست آزمون ها',
  consultants: ' مشاوران ',
  course: ' درسی ',
  lifeStyle: ' سبک زندگی ',
  openQuiz: 'لیست آزمون های باز',
  onlineStanding: 'آزمون های آنلاین استندیگ',
  schoolQuiz: 'لیست آزمون های مدرسه',
  advisorQuiz: 'لیست آزمون های مشاور',
  iryscQuiz: 'لیست آزمون های آیریسک',
  customQuiz: 'لیست آزمون های شخصی',
  contentQuiz: 'لیست آزمون های مخصوص بسته های آموزشی',
  packageQuiz: 'بسته های آزمون',
  haveQuiz: 'آزمون های موجود',
  name: 'نام',
  addBatch: 'افزودن دسته ای',
  questions: 'سوالات',
  question: 'سوال',
  showMore: 'نمایش بیشتر',
  showLess: 'نمایش کمتر',
  more: 'اطلاعات بیشتر',
  less: 'اطلاعات کمتر',
  from: 'از ',
  to: ' تا ',
  visibility: 'وضعیت نمایش',
  select: 'انتخاب',
  selected: 'انتخاب شده',
  selectAll: 'انتخاب همه',
  back: 'بازگشت',
  unit: 'واحد',
  Learn: 'آموزش',
  nes: 'فوریت',
  view: 'مشاهده',
  forView: 'برای مشاهده',
  finished: 'خاتمه شده',
  date: 'تاریخ',
  spinGift: 'گردونه شانس',
  winList: 'لیست برند گان',
  selectGift: 'مشخص کردن جوایز',
  priority: 'اولویت',
  used: 'استفاده شده',
  coin: 'ایکس پول',
  money: 'پول',
  counter: 'تعداد',
  dateExpire: 'تاریخ انقضا',
  prob: 'احتمال',
  addDate: 'اضافه کردن تاریخ',
  web: 'وب',
  app: 'اپ',
  print: 'چاپ',
  tarazLevels: 'سطوح تراز',
  level: 'مقطع',
  successOffCode: 'کد تخفیف موردنظر با موفقیت اعمال گردید',
  shouldLogin: 'لطفا ابتدا لاگین کنید',
  transactionResult: 'نتیجه تراکنش',
  successTransaction: 'تراکنش موردنظر با موفقیت انجام شد.',
  removeSuccessfully: 'فایل موردنظر با موفقیت حذف گردید',
  transactionFinantial: 'تراکنش های مالی',
  section: 'مورد استفاده',
  recp: 'رسید پرداخت',
  downloadRecp: 'دریافت رسید پرداخت',
  start: 'شروع',
  go: 'بروید',
  clickHere: 'اینجا را کلیک کنید',
  filter: 'اعمال فیلتر',
  contents: 'بسته های آموزشی',
  listContents: 'لیست بسته های آموزشی',
  faqContents: 'سوالات متداول',
  advContents: 'ویدیوهای تبلیغاتی',
  seoContents: 'سئو',
  results: 'نتایج',
  free: 'رایگان',
  clearFilters: 'پاک کردن فیلترها',
  showFilters: 'نمایش فیلتر',
  has: 'دارد',
  not_has: 'ندارد',
  col: ': ',
  questionReportTags: 'تگ های گزارش خرابی سوال',
  educationalHistory: 'سوابق تحصیلی',
  birthDay: 'تاریخ تولد',
};
export default translator;
