const Translate = {
  makeQuiz: 'آزمون خود را بسازید',
  nameTitle: 'نام آزمون',
  name: 'نام',
  nameHelp: 'لطفا یک نام برای آزمون خود انتخاب کنید',
  chooseAndAdd: 'انتخاب و اضافه کنید',
  line: 'رشته',
  choose: 'انتخاب',
  lessons: 'نمایش دروس',
  subjects: 'نمایش حیطه ها',
  difficulty: 'درجه سختی : ',
  count: 'تعداد سوال',
  sortQuiz: 'ترتیب را مشخص کنید',
  transBack: 'انتقال به قبل از',
  numberOfQuiz: 'شماره سوال',
  questionCounts: 'تعداد سوالات: ',
  minChar: 'حداقل سه کاراکتر وارد نمایید',
  search: 'جست و جو',
  searchQuestion: 'جست و جو در سوالات',
  goToQuiz: 'تایید و مشاهده سوالات افزوده شده',
  searchInAll: 'نام رشته و یا درس و یا مبحث و یا طراح',
  searchInAllHelp: 'برای مشاهده رشته ها بر روی آیکون جست و جو کلیک کنید',
  searchSubText:
    'نام رشته و یا درس و یا مبحث و یا طراح موردنظر خود را جست و جو کنید و یا از دسته های زیر استفاده کنید',
  orUseCats: 'یا از دسته های زیر استفاده کنید',
  easy: ' آسان - ',
  mid: ' متوسط - ',
  hard: ' سخت ',
  addAndContinue: 'افزودن و ادامه ساخت آزمون',
  addAndGoToQuiz: 'افزودن و رفتن برای پرداخت',
};

export default Translate;
