export const Translate = {
  dashboard: 'داشبورد مدیریتی',
  pendingChunks: 'جلسات چانک نشده',
  pendingTickets: 'تیکت‌های پاسخ داده نشده',
  pendingComments: 'تعداد نظرات بررسی نشده',
  pendingSettleRequests: 'درخواست‌های تسویه برررسی نشده',
  pendingRequestForAdvisorAnswer: 'درخواست‌های مشاوره پاسخ داده نشده',
  pendingRequestForStudentPay: 'درخواست‌های مشاوره در انتظار پرداخت',
  lastMonthKarbargs: 'تعداد کاربرگ‌های 30 روز گذشته',
  lastMonthMeetings: 'تعداد جلسات آنلاین 30 روز گذشته',
  lastMonthSettled: 'تعداد تسویه‌های انجام شده 30 روز گذشته',
  lastMonthOpenQuizRegistry: 'تعداد آزمون‌های باز خریداری شده در 30 روز گذشته',
  lastMonthCustomQuizRegistry: 'تعداد آزمون‌های شخصی 30 روز گذشته',
  lastMonthContentBuyCount: 'تعداد خریداران بسته‌های آموزشی 30 روز گذشته',
  lastMonthTutorialCount: 'تعداد تدریس‌های خصوصی 30 روز گذشته',
  pendingUpgradeLevelRequests: 'درخواست‌های ارتقای سطح در انتظار تایید',
  lastMonthAdviceMeetings: 'تعداد جلسات مشاوره در 30 روز گذشته',
  lastMonthTeachReportsCount: 'مشکلات گزارش شده درباره تدریس در 30 روز گذشته',
  activeTeachers: 'تعداد مدرسان فعال',
  activeAdvisors: 'تعداد مشاوران فعال',
  showLastSettleRequest: 'نمایش آخرین درخواست‌های تسویه',
  showIncomingRequestsForAdvice:
    'نمایش درخواست‌های رسیده برای مشاوره در انتظار تایید',
  showIncomingRequestsForTeach: 'نمایش درخواست‌های تدریس در انتظار تایید',
  showLastUserReports: 'نمایش آخرین گزارشات مشکل',
  showMeetings: 'نمایش جلسات آنلاین کنونی',
  showTopAdvisors: 'نمایش برترین مشاوران',
  showTopTeachers: 'نمایش برترین دبیران',
  showTopLastWeekBestSellerContents:
    'نمایش پرفروش‌ترین محتواهای آموزشی 7 روز گذشته',
  showDashboard: 'نمایش آمار کلی',
  studentsCount: 'تعداد دانش آموزان فعلی',
  commentsCount: 'تعداد کامنت‌ها',
  topAdvisors: 'مشاوران برتر 30 روز گذشته',
  topLastWeekBestSeller: 'بسته‌های پرفروش هفته',
};
