const Translator = {
  list: 'لیست بسته های آموزشی ',
  sessionsList: 'لیست جلسات بسته های آموزشی ',
  title: 'نام بسته',
  teacher: 'نام دبیر',
  price: 'قیمت',
  priority: 'اولویت',
  sessionsCount: 'تعداد جلسات',
  hasCert: 'آیا گواهی دارد؟',
  hasExam: 'آیا آزمون دارد؟',
  duration: 'مدت دوره',
  sessionDuration: 'مدت جلسه',
  sessionDurationHelp: 'مدت جلسه (به ثانیه)',
  buyers: 'تعداد خریداران',
  hasFinalExam: 'آیا آزمون پایان دوره دارد؟',
  finalExamMinMark: 'حداقل نمره قبولی آزمون پایان دوره',
  finalExam: 'آزمون پایان ترم',
  addNewItem: 'افزودن بسته آموزشی جدید',
  addNewSession: 'افزودن جلسه جدید',
  editItem: 'ویرایش بسته آموزشی',
  editSession: 'ویرایش دوره ',
  description: 'درباره دوره',
  sessionDescription: 'درباره این جلسه',
  teacherBio: 'درباره استاد',
  preReq: 'پیش نیاز های دوره',
  cert: 'گواهی دوره',
  tags: 'برچسب ها',
  seeInfo: 'مشاهده اطلاعات',
  sessions: 'مدیریت جلسات',
  users: 'گزارش گیری خریداران',
  image: 'تصویر شاخص',
  attaches: 'فایل های ضمیمه',
  attachesCount: 'تعداد فایل های ضمیمه',
  video: 'فایل ویدیو جلسه',
  sessionTitle: 'عنوان جلسه',
  sessionPriceHelp: 'قیمت (این فیلد اختیاری است)',
  hasVideo: 'آیا فایل ویدیو بارگذاری شده است؟',
};

export default Translator;
