const translator = {
  uploadExcelFile: 'بارگذاری فایل اکسل سوالات',
  uploadZipFile: 'بارگذاری فایل زیپ سوالات',
  addBatch: 'افزودن دسته ای سوالات',
  addBatchFiles: 'افزودن دسته ای فایل صورت/پاسخ سوالات',
  qNo: 'تعداد سوالات',
  questions: 'مدیریت سوالات',
  subject: 'مبحث',
  lesson: 'درس',
  grade: 'مقطع',
  addQuestions: 'افزودن سوالات',
  criticalThresh: 'حد آستانه کمبود سوالات',
  justCriticals: 'تنها مباحث دارای کمبود سوال را نمایش بده',
  organizationCode: ' کد سازمانی : ',
  neededTime: ' زمان پاسخدهی : ',
  author: ' مولف : ',
  kind: ' نوع پاسخ : ',
  level: ' درجه سختی : ',
  choicesCount: ' تعداد گزینه :  ',
  telorance: ' تلورانس پاسخ : ',
  answer: 'پاسخ صحیح  : ',
  questionFile: 'فایل سوال',
  answerFile: 'فایل پاسخ',
  typeOfQuestion: ' نوع سوال : ',
  longTime: 'مدت زمان :  ',
  minuts: ' دقیقه ',
  second: ' ثانیه ',
  easy: 'آسان',
  mid: 'متوسط',
  hard: 'سخت',
  visibility: 'وضعیت نمایش : ',
  showResult: 'مشاهده سوالات',
  statusTrue: 'فعال',
  statusFalse: 'غیرفعال',
  test: 'تستی',
  tashrihi: 'تشریحی',
  shortAnswer: 'پاسخ کوتاه',
  multiSentence: 'پاسخ چند جمله',
  sentencesCount: 'تعداد گزاره  ها :',
  neededLines: 'تعداد خطوط : ',
  addQuiz: 'افزودن به آزمون',
};

export default translator;
