const Translate = {
  number: 'شماره',
  addBookmark: 'نشان کردن سوال',
  deleteBookmark: 'حذف نشان کردن سوال',
  description: 'شرح سوال',
  answerFile: 'پاسخ تشریحی',
  res: 'انتخاب پاسخ',
  yourAnswer: 'پاسخ شما',
  answer: 'پاسخ صحیح',
  choice: 'گزینه ',
  resInput: 'ورود پاسخ',
  status: 'وضعیت کلی',
  questionRes: 'سوالات پاسخ داده شده ',
  questionNoAnswer: 'سوالات بدون پاسخ',
  review: 'مرور آزمون',
  continue: 'ادامه آزمون',
  start: 'شروع آزمون',
  quizList: 'لیست سوالات',
  help: 'راهنما',
  answered: 'پاسخ داده شده',
  quizNoneRes: 'بدون پاسخ',
  bookmarked: 'نشان شده',
};

export default Translate;
