export const Translate = {
  contentBuyers: 'خریداران دوره‌های آموزشی',
  openQuizBuyers: 'خریداران آزمون‌های باز',
  customQuizBuyers: 'خریداران آزمون شخصی',
  adviceBuyers: 'خریداران بخش مشاوره',
  regularQuizBuyers: 'خریداران آزمون‌های آیریسک',
  content: 'دوره‌های آموزشی',
  openQuiz: 'آزمون‌های باز',
  regularQuiz: 'آزمون‌های آیریسک',
  advice: 'مشاوره',
  customQuiz: 'آزمون‌های شخصی',
  all: 'همه',
  section: 'بخش',
  from: 'تاریخ آغاز فیلتر',
  to: 'تاریخ پایان فیلتر',
  advisorName: 'نام مشاور',
  contentAggregateReport: 'گزارش تجمعی از فروش دوره‌های آموزشی',
  openQuizAggregateReport: 'گزارش تجمعی از فروش آزمون‌های باز',
  regularQuizAggregateReport: 'گزارش تجمعی از فروش آزمون‌های آیریسک',
  adviceAggregateReport: 'گزارش تجمعی از فروش بخش مشاوره',
};
