const translator = {
  username: 'نام کاربری',
  password: 'رمزعبور',
  confirm: 'تایید',
  phone: 'شماره تلفن همراه',
  mail: 'ایمیل',
  signUp: 'ثبت نام',
  NID: 'کد ملی',
  firstname: 'نام',
  lastname: 'نام خانوادگی',
  congratulations: 'تبریک',
  chooseOne: 'لطفا یکی از گزینه های زیر را انتخاب کنید',
  student: 'دانش آموز',
  students: 'دانش آموزان',
  teacher: 'دبیر',
  agent: 'نماینده',
  agents: 'نمایندگان',
  school: 'مدرسه',
  schools: 'مدارس',
  advisor: 'مشاور',
  entrance: 'ورود',
  continue: 'ادامه',
  support: 'پشتیبانی',
  home: 'خانه',
  myQuizes: 'آزمون های من',
  buyQuiz: 'خرید آزمون',
  quizes: 'آزمون ها',
  avatars: 'مدیریت تصاویر آواتار',
  charge: 'شارژ',
  history: 'سابقه',
  config: 'تنظیمات',
  configuration: 'پیکربندی',
  generalConfiguration: 'پیکربندی کلی',
  ravanConfiguration: 'پیکربندی آزمون های روان شناسی',
  requests: 'درخواست ها',
  users: 'کاربران',
  pleaseFillAllFields: 'لطفا تمام فیلدهای لازم را پر نمایید.',
  invalidFieldValue: 'مقدار وارد شده صحیح نمی باشد.',
  opErr: 'خطایی در انجام عملیات موردنظر رخ داده است',
  noResult: 'نتیجه ای یافت نشد',
  necessary: 'ضروری',
  necessaryField: 'این فیلد ضروری است.',
  cancel: 'انصراف',
  sex: 'جنسیت',
  state: 'استان',
  city: 'شهر',
  grade: 'پایه تحصیلی',
  branch: 'گروه آموزشی',
  change: 'تغییر',
  doChange: 'اعمال تغییر',
  confirmChanges: 'ثبت تغییرات',
  horizontal: 'افقی',
  vertical: 'عمودی',
  center: 'مرکز:',
  nextStep: 'مرحله بعد',
  desc: 'توضیحات',
  optional: 'اختیاری',
  yes: 'بله',
  no: 'خیر',
  hide: 'عدم نمایش',
  show: 'نمایش',
  optionalFalseDefault: 'اختیاری(پیش فرض این فیلد خیر است)',
  optionalTrueDefault: 'اختیاری(پیش فرض این فیلد بله است)',
  chooseFile: 'انتخاب فایل',
  uploading: 'در حال آپلود',
  pleaseWait: 'لطفا شکیبا باشید',
  fileAdressFor: 'آدرس فایل آپلود شده برای',
  copyLink: 'کپی کردن لینک',
  copied: 'کپی شد!',
  delete: 'حذف',
  upload: 'بارگذاری فایل',
  notChooseFile: 'هنوز فایلی انتخاب نشده است',
  maxSize: 'حداکثر حجم ',
  format: 'فرمت',
  success: 'عملیات موردنظر با موفقیت انجام شد',
  paid: 'مقدار پرداختی',
  searchBy: 'خصوصیت یکتا',
  nameAndLast: 'نام و نام خانوادگی',
  search: 'جست و جو',
  wantedUser: 'دانش آموز موردنظر',
  deleteAll: 'حذف همه',
  edit: 'ویرایش',
  opMenu: 'منو عملیات',
  op: 'عملیات کلی',
  operation: 'عملیات',
  sureRemove: 'آیا از حذف آیتم/آیتم های موردنظر اطمینان دارید؟',
  NIDs: 'کد ملی دانش آموزان مدنظر',
  NIDHelp: 'چندین کد ملی را با استفاده از , جدا کنید',
  createdAt: 'زمان ایجاد',
  advancedSearch: 'جستجوی پیشرفته',
  update: 'ویرایش',
  all: 'همه',
  pageNotFound: 'صفحه موردنظر یافت نشد.',
  sampad: 'سمپاد',
  gheyr: 'غیرانتفاعی',
  sayer: 'سایر',
  nemone: 'نمونه دولتی',
  dolati: 'دولتی',
  aval: 'متوسطه اول',
  dovom: 'متوسطه دوم',
  dabestan: 'دبستان',
  address: 'آدرس',
  searchUser: 'یافتن دانش آموز',
};
export default translator;
