const translator = {
  username: 'نام کاربری',
  password: 'رمزعبور',
  confirm: 'تایید',
  phone: 'شماره تلفن همراه',
  mail: 'ایمیل',
  signUp: 'ثبت نام',
  NID: 'کد ملی',
  firstname: 'نام',
  lastname: 'نام خانوادگی',
  congratulations: 'تبریک',
  chooseOne: 'لطفا یکی از گزینه های زیر را انتخاب کنید',
  student: 'دانش آموز',
  teacher: 'دبیر',
  agent: 'نماینده',
  school: 'مدرسه',
  advisor: 'مشاور',
  entrance: 'ورود',
  continue: 'ادامه',
  support: 'پشتیبانی',
  home: 'خانه',
  myQuizes: 'آزمون های من',
  buyQuiz: 'خرید آزمون',
  charge: 'شارژ',
  history: 'سابقه',
  config: 'تنظیمات',
  pleaseFillAllFields: 'لطفا تمام فیلدهای لازم را پر نمایید.',
  invalidFieldValue: 'مقدار وارد شده صحیح نمی باشد.',
  opErr: 'خطایی در انجام عملیات موردنظر رخ داده است',
  necessary: 'ضروری',
  necessaryField: 'این فیلد ضروری است.',
};
export default translator;
