const translator = {
  uploadExcelFile: 'بارگذاری فایل اکسل سوالات',
  uploadZipFile: 'بارگذاری فایل زیپ سوالات',
  uploadPDFFile: 'بارگذاری فایل PDF سوالات',
  addBatch: 'افزودن دسته ای سوالات',
  addBatchFiles: 'افزودن دسته ای فایل صورت/پاسخ سوالات',
  qNo: 'تعداد سوالات',
  questions: 'مدیریت سوالات',
  subject: 'مبحث',
  lesson: 'درس',
  grade: 'مقطع',
  tag: 'تگ ها',
  addQuestions: 'افزودن سوالات',
  criticalThresh: 'حد آستانه کمبود سوالات',
  justCriticals: 'تنها مباحث دارای کمبود سوال را نمایش بده',
  organizationCode: ' کد سازمانی : ',
  neededTime: ' زمان پاسخدهی : ',
  author: ' مولف : ',
  kind: ' نوع پاسخ : ',
  level: ' درجه سختی : ',
  choicesCount: ' تعداد گزینه :  ',
  telorance: ' تلورانس پاسخ : ',
  year: ' سال : ',
  answer: 'پاسخ صحیح  : ',
  typeOfQuestion: ' نوع سوال : ',
  minuts: ' دقیقه ',
  second: ' ثانیه ',
  easy: 'آسان',
  mid: 'متوسط',
  hard: 'سخت',
  visibility: 'وضعیت نمایش : ',
  showResult: 'مشاهده سوالات',
  statusTrue: 'فعال',
  statusFalse: 'غیرفعال',
  test: 'تستی',
  tashrihi: 'تشریحی',
  shortAnswer: 'پاسخ کوتاه',
  multiSentence: 'چند گزاره ای',
  sentencesCount: 'تعداد گزاره ها :',
  neededLine: 'تعداد خطوط : ',
  addQuiz: 'افزودن به آزمون',
  questionFile: 'فایل صورت سوال',
  answerFile: 'فایل پاسخ سوال(اختیاری)',
  levelQuestion: 'سطح سختی سوال',
  questionShowEasy: 'نمایش سوالات آسان',
  questionShowMid: 'نمایش سوالات متوسط',
  questionShowHard: 'نمایش سوالات سخت',
  questionNumber: 'تعداد سوالات موجود: ',
};

export default translator;
